version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      # MYSQL_DATABASE: 'restful_api_facebook'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Arifin123!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Arifin123!'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./docker/database:/var/lib/mysql
  redis:
    image: redis:7.2.5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/root/redis
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      # - REDIS_DATABASES=16
# Names our volume
volumes:
  database:



# migrate create -ext sql -dir db/migrations -seq users
# migrate -database 'mysql://root:Arifin123!@tcp(127.0.0.1:3306)/bwastartup?charset=utf8mb4&parseTime=True&loc=Local' -path db/migrations up
# migrate -path db/migrations -database 'mysql://root:Arifin123!@tcp(127.0.0.1:3306)/bwastartup?charset=utf8mb4&parseTime=True&loc=Local' force 1
